### ISSUE TITLE
can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by ayavuzcakir** [KChen-lab/Monopogen#10]
I wanted to try Monopogen on my GEX-cellranger output, first started with preprocess.py, however, it directly gave me the following error;

> **Traceback (most recent call last):
>   File "/path/Monopogen/src/Monopogen.py", line 435, in <module>
>     main()
>   File "/path/Monopogen/src/Monopogen.py", line 428, in main
>     args.func(args)
>   File "/path/Monopogen/src/Monopogen.py", line 291, in preProcess
>     for line in f_in:
>   File "/miniconda3/lib/python3.9/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte**
> 
My BAM file is not gzipped, I even tested with different BAM files but the result was the same, I looked into the source code and saw that it tries to open a BAM file with "with open" and seems like it causes the error,  can you please help regarding this one?

**Comment by jinzhuangdou** [comment]
Hi, Monopogen uses the function pysam.AlignmentFile to load the bam files. Would you mind share with me a subset of your bam files so that I can examine what happens inside?
