### ISSUE TITLE
About run Somatic SNV calling from scRNA-seq 

### ISSUE THREAD

**Issue by monoplasty** [KChen-lab/Monopogen#16]
Hello,
Thank you for developing such a wonderful method.
I use single-cell sequencing data to run Somatic SNV calling from scRNA-seq, but I don't know how to prepare the cell barcode file. Because the barcode.tsv file produced by cellranger has only one column, and the csv file given in the case has 2 columns, I don’t know what the id in the second column means? How to prepare this file? Can a randomly generated non-repeating serial number be used?

Could you please provide some guidance on how to resolve this issue?
Thank you in advance for your assistance.

**Comment by jinzhuangdou** [comment]
Hi the second column is the number of reads detected in the cell which could be from Seurat object.

**Comment by jinzhuangdou** [comment]
You can select top N cells based on your own dataset

**Comment by Joyjoyjoyc** [comment]
> Hello, Thank you for developing such a wonderful method. I use single-cell sequencing data to run Somatic SNV calling from scRNA-seq, but I don't know how to prepare the cell barcode file. Because the barcode.tsv file produced by cellranger has only one column, and the csv file given in the case has 2 columns, I don’t know what the id in the second column means? How to prepare this file? Can a randomly generated non-repeating serial number be used?
> 
> Could you please provide some guidance on how to resolve this issue? Thank you in advance for your assistance.

Hi, 

> Hello, Thank you for developing such a wonderful method. I use single-cell sequencing data to run Somatic SNV calling from scRNA-seq, but I don't know how to prepare the cell barcode file. Because the barcode.tsv file produced by cellranger has only one column, and the csv file given in the case has 2 columns, I don’t know what the id in the second column means? How to prepare this file? Can a randomly generated non-repeating serial number be used?
> 
> Could you please provide some guidance on how to resolve this issue? Thank you in advance for your assistance.

Hi, I would like to know if the bam.lst required in the germline step can contain multiple BAM files. Also, in the somatic step, does the barcode.tsv include only one sample? Thank you!
