### ISSUE TITLE
"somatic mutation module is still in the development stage"

### ISSUE THREAD

**Issue by AhmedArslan** [KChen-lab/Monopogen#2]
Hi, 
I wanted to know about timeline for the final version release of the somatic mutation detection module? 
Thanks.

**Comment by jinzhuangdou** [comment]
Currently the somatic mutation part can be identified after monomer-calling in cluster/cell type level.

**Comment by jinzhuangdou** [comment]
The somatic module has been implemented now. Please give it a try
