### ISSUE TITLE
missing a space between flag and file name

### ISSUE THREAD

**Issue by fulabgenomics** [KChen-lab/Monopogen#20]
Hi there,
Thanks for the great tool!
I followed the manual for calling the somatic mutations
```
path="/SNV/Monopogen"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps
#python  ${path}/src/Monopogen.py  preProcess -b bam.list3 -o bm  -a ${path}/apps -t 2
python ${path}/src/Monopogen.py  germline  -a ${path}/apps  -r region.lst \
 -p ./  -t 22 \
 -g  genome.fa  -m 3 -s all  -o bm
```
with bam.list3 like this
$cat bam.list3
`bm,/SNV/Monopogen/test/chr20.maester_scRNA.bam`

I successfully have the bm_chr20.filter.bam from the first step, then I got errors 
```
Exception in thread "main" java.lang.IllegalArgumentException: Missing line (#CHROM ...) after meta-information lines
File source: bm/germline/chr20.germline.vcf
```

when I double-check the script file that it automatically generated,

$cat bm/Script/runGermline_chr20.sh
`/SNV/Monopogen/apps/samtools mpileup -bout/Bam/chr20.filter.bam.lst -f chr20_2Mb.hg38.fa -r chr20 -q 20 -Q 20 -t DP -d 10000000 -v  | .....`

I think the correct code should be  `-b out/Bam/chr20.filter.bam.lst ....` but somehow there is no space between the -b and the file name, maybe a space in line 77 of `Monopogen.py` is needed.

Thanks!

**Comment by fulabgenomics** [comment]
and when I ran the next step with
```
python  ${path}/src/Monopogen.py  somatic  \
    -a   ${path}/apps  -r  region.lst  -t 50 \
    -i  bm  -l  CB_7K.maester_scRNA.csv   -s featureInfo     \
    -g  refdata-gex-GRCh38-2020-A/fasta/genome.fa 
```
 I go error
```[2023-10-04 17:21:21,662] INFO     Monopogen.py Get feature information from sequencing data...
[E::idx_find_and_load] Could not retrieve index file for 'bm/germline/chr20.phased.vcf.gz'
[W::vcf_parse] Contig 'chr20' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for 'bm/germline/chr20.gl.vcf.gz'
```
Right now I tried manually indexing the files to get around it, can the index step be added to the `runGermline_chr20.sh`? in the future? Thank you so much!

**Comment by jinzhuangdou** [comment]
Thanks. It is weired that there is no space in the -b option. The index process has been fixed now.

**Comment by fulabgenomics** [comment]
Thank you very much for your prompt response! The pipeline now works perfectly with my data, so I will go ahead and close this comment. Thanks for the tool once again.
