### ISSUE TITLE
About  Error for the cellScan step during Somatic Variant Calling

### ISSUE THREAD

**Issue by neuroniko** [KChen-lab/Monopogen#25]
Dear Monopogen developers,
I'd like to express my gratitude for developing Monopogen. It has been invaluable for my research. I've encountered an issue and was hoping to seek your guidance on it.
When I doing the cellScan step in Somatic Variant Calling, I got an error: with Monopogen.py Get single cell level information from sequencing data...['chr17']['chr17.filter.targeted.bam'] merge: invalid option -- 'o'
I checked the code in Monopogen.py file, it uses pysam.merge("-f","-o",output_bam,*bamlst), this error seems due to pysam version difference. I changed the code into pysam.merge("-f", output_bam, *bamlst), and it works. However, I created the environment exactly as yours(pysam=0.16.0.1), I don't know If it will change the output. If not,  I hope this could help others who encounter this issue.

**Comment by neuroniko** [comment]
After I update Pysam to 0.21, it also works.

**Comment by jinzhuangdou** [comment]
Thanks for letting me know.
