### ISSUE TITLE
Imprinted genes identification

### ISSUE THREAD

**Issue by singcell** [KChen-lab/Monopogen#37]
Thanks for developing a nice tool and wanted to leverage its capabilities in my research. A few questions:

Using a reciprocal matings, I have generated two stem cell lines by mating two distinct mouse strains with characterized SNPs. I have performed scRNA-seq on these stem cell lines from both reciprocal matings/crosses. I am specifically interested in identifying imprinted genes within this dataset using your program. Can you please advise on the best approach to integrate my SNP and scRNA-seq data into your tool for this purpose?  

Due to their sequencing bias, DropSeq methods like 10x can miss SNPs outside the captured 5' or 3' transcript ends. Do you have any suggestion?

Thank you!

**Comment by jinzhuangdou** [comment]
Hi, are you working on mouse model? Monopogen only works on SNV calling from human since we need the 1KG3 reference panel for imputation.

**Comment by singcell** [comment]
> Hi, are you working on mouse model? Monopogen only works on SNV calling from human since we need the 1KG3 reference panel for imputation.

Thank you of your reply. Yes, I have mouse dataset to analyze.
