### ISSUE TITLE
Can Monopogen use for calling variants in Malaria parasite single cell Data ?

### ISSUE THREAD

**Issue by MJBioInfo** [KChen-lab/Monopogen#39]
Dear Monopogen developers ,
Is it possible to call variants on single cell data from Malaria parasite ? If yes How LD works . DO we need to prepare some files ?

your valuable suggestions is greatly appreciated

**Comment by jinzhuangdou** [comment]
Unfortunately monopogen only works on human genomics data. The LD is constructed on 1KG3 population panel.

**Comment by xinghua1001** [comment]
Hi Dr. Dou, 
If I have some population genetic data for my species (more than 100 individuals), can I use it for monopogen on this species?

**Comment by jinzhuangdou** [comment]
Yes, you can build your own reference panel (similar with 1KG3) and then run Monopogen. Maybe you can follow beagle manual (http://faculty.washington.edu/browning/beagle/beagle.html).
