### ISSUE TITLE
Run monopogen for more than 1 sample?

### ISSUE THREAD

**Issue by ZhengJIN94** [KChen-lab/Monopogen#43]
Hi, 

I have run preprocess and germline calling steps for 9 scRNA-seq samples (10x genomics data).

Now, I hope to call somatic mutation, and I have a question about the cell barcode files. 

How should I prepare the cell barcode file? Put all cells of 9 samples in one file? 

However, in 10x genomics data, if we do not add index to cell barcode, there will be several duplication barcodes, can monopogen recognize the index part (such as AAACCCAAGCATTTGC-1_1_1_1_1_1 or sample1_AAACCCAAGCATTTGC-1) ?

Or, I should run it one by one from the initial (preprocess) step?

Thank you, so much!

**Comment by jinzhuangdou** [comment]
You use joint-calling mode for germline calling or run germline calling one by one? 

If you want to call somatic SNVs, you need to run germline module for each sample (i.e, only set one sample in bam.lst).

**Comment by jinzhuangdou** [comment]
In such case, you need to prepare bam.S1.lst, bam.S2.lst, ..., bam.S9.lst.
