### ISSUE TITLE
Lineage tracing

### ISSUE THREAD

**Issue by SofiaFreiman** [KChen-lab/Monopogen#45]
Hello!

I would like to perform lineage tracing with Monopogen on my single-cell RNA-Seq data. \
I followed the tutorial to the end and got following files in the somatic folder: \
_chr17.cell_snv.cellID.csv_ \
_chr17.germlineTwoLoci_model.csv_ \
_chr17.cell_snv.cellID.filter.csv  \
chr17.cell_snv.snvID.csv \
chr17.putativeSNVs.csv \
chr17.germlineTrioLoci_model.csv \
chr17.gl.filter.hc.cell.mat.gz   \
chr17.cell_snv.mat.gz \
chr17.gl.vcf.filter.hc.pos \
chr17.gl.vcf.filter.hc.bed \
chr17.SNV_mat.RDS \
 chr17.gl.vcf.DP4 \
chr17.gl.vcf.filter.DP4 \
LDrefinement_germline.chr17.pdf \
svm_feature.chr17.pdf_

Could you direct me where I can find information about these output files?

Filtering _putativeSNVs.csv_ file with suggested parameters (_(df.SVM_pos_score>0.5) & (df.LDrefine_merged_score>0.25) & (df.BAF_alt>0.1) & (df.BAF_alt<0.5) & (df.Depth_ref>2) & (df.Depth_alt>2)_) gave me 111 variants. \
How can I translate these variants on single-cell level to identify groups of cells with same origin?

**Comment by jinzhuangdou** [comment]
Hi, you can access the SNV by cell information from chr17.SNV_mat.RDS. There are recording information for wild and mutated alleles for each cell that can be used for downstream analysis. You need to pay attention on the definition of each element in the matrix.  A/B: A denotes number of reads supporting wild allele, B denotes number of reads supporting mutated allele.
