### ISSUE TITLE
can the somatic module identify indels?

### ISSUE THREAD

**Issue by ad2n15** [KChen-lab/Monopogen#66]
Thank you for developing this tool. I run the tool following somatic module, but I can not find any indels in the final somatic csv files. Do you have an explanation?

**Comment by jinzhuangdou** [comment]
Monopogen can identify INDELs in germline modules. However, the current motif-based search does not detect INDELs in the somatic module. If you already have candidate INDELs, you can check their sequencing depth in the `./germline/chr*.gl.DP4` file to verify their presence.

**Comment by jinzhuangdou** [comment]
We are planing to give an updated version to handle INDELs in somatic module soon.

**Comment by ad2n15** [comment]
Thank you for your reply
