### ISSUE TITLE
installation & versions

### ISSUE THREAD

**Issue by swvanderlaan** [KChen-lab/Monopogen#71]
Hi,

You mentioned to have added the different tools you use as an 'app'. However, this doesn't work on our HPC, so I need to install them inside a specific environment. I created one, but... You mentioned to compile specific version of the tools:

```
samtools Version: 1.2 (using htslib 1.2.1)
bcftools Version: 1.8 (using htslib 1.8)
beagle.27Jul16.86a.jar (version 4.1)
tabix Version: 1.9
bgzip Version: 1.9
```

However, `tabix` version 1.9 comes with `htslib 1.9` which conflicts with the version you mention for `bcftools` and `samtools`. So, my question: which version should I be using? 

Also, in the `app` folder, you have `vcftools`. Which version should that be? 

Thanks!

**Comment by swvanderlaan** [comment]
To add some background. Here's what I did. 

**Step 1: install R**

```
cd /path_to_software
mkdir -v R-4.4.1 # (currently the latest version)
mkdir -v tmp
cd /tmp
wget http://cran-mirror.cs.uu.nl/src/base/R-3/R-4.4.1.tar.gz
tar -zxvf R-4.4.1.tar.gz
cd R-4.4.1
./configure --prefix=/path_to_software/R-4.4.1 --enable-java=no
make
make install
```

Next, install some R packages:

```
install.packages("e1071")
install.packages("ggplot2")
install.packages("data.table")
```

**Step 2: create monopogen environment**

We have `mambaforge3` installed on our cluster (and my macOS Sequoia), so:

```
mamba create --name monopogen python=3.7
mamba activate monopogen 
mamba install openjdk">=1.8.0" pandas">=1.2.3" pysam">=0.16.0.1" numpy">=1.19.5" scipy">=1.6.3" pillow">=8.2.0"
mamba install bioconda::samtools"==1.2"
mamba install bioconda::bcftools"==1.8"
mamba install bioconda::htslib"==1.9" # I chose this one for now, since that is linked to the right version for tabix and bgzip
```

**Comment by swvanderlaan** [comment]
So even with the above instructions, and exact versions you stipulated I get this error:

```
Traceback (most recent call last):
  File "src/Monopogen.py", line 437, in <module>
    main()
  File "src/Monopogen.py", line 431, in main
    args.func(args)
  File "src/Monopogen.py", line 223, in preProcess
    for line in f_in:
  File "miniforge3/envs/monopogen37/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Any advice how to solves this?

**Comment by swvanderlaan** [comment]
> So even with the above instructions, and exact versions you stipulated I get this error:
> 
> ```
> Traceback (most recent call last):
>   File "src/Monopogen.py", line 437, in <module>
>     main()
>   File "src/Monopogen.py", line 431, in main
>     args.func(args)
>   File "src/Monopogen.py", line 223, in preProcess
>     for line in f_in:
>   File "miniforge3/envs/monopogen37/lib/python3.7/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
> ```
> 
> Any advice how to solves this?

I figured out this issue, it's related to [this post](https://github.com/KChen-lab/Monopogen/issues/10). One should provide a specific `.bam`-file, rather a list of `.bam`-files - my bad, I hadn't properly looked at the example-script provided. I edited the `--bamFile` flag description to match this requirement.

**Comment by swvanderlaan** [comment]
I forked this repository and created a [wiki](https://github.com/swvanderlaan/Monopogen/wiki) - mainly for myself - on how to install the required packages. 

So far using the recent versions of `samtools`, `vcftools` and `bcftools` work just fine _after_ editing a few lines of code in `Monopogen.py`.

**Comment by ainsku** [comment]
Thanks @swvanderlaan for the wiki, it helped me a lot making my environment. I had an issue with libcrypto.so files with bcftools, updating to 1.9 seems to have fixed the issue for me for now.

Best,
Aino
