### ISSUE TITLE
gremlin snvs on a per cell basis

### ISSUE THREAD

**Issue by aidanshoham12** [KChen-lab/Monopogen#76]
Hello
Is there a way to use Monopogen to detect gremlin SNVs on a per cell basis in the same way that somatic snvs are called?
Thank you!

**Comment by jinzhuangdou** [comment]
We are expanding Monopogen to include reference and alternative read detection per cell for germline SNVs. A release will be available later.

**Comment by jinzhuangdou** [comment]
Yes, the current version of Monopogen can output the SNV-by-cell matrix, which includes both germline and somatic SNVs. Each element in the SNV-by-cell matrix will represent the depth of wild-type and alternative reads

**Comment by apal6** [comment]
Hi, I would like to follow up on the release where I could run monopogen on reference and query reads from single cell data? Thank you!
