### ISSUE TITLE
Program beagle.08Feb22.fa4.jar  cannot be found 

### ISSUE THREAD

**Issue by wkdeng** [KChen-lab/Monopogen#80]
In germline.py, the program checked existence of both beagle.08Feb22.fa4.jar and beagle.27Jul16.86a.jar, but beagle.08Feb22.fa4.jar is not provided in apps folder.

**Comment by jinzhuangdou** [comment]
I have removed the beagle.08Feb22.fa4.jar file, and the application check will skip this verification. Please try the updated version.
