### ISSUE TITLE
Empty .gl.vcf.gz files running example data. 

### ISSUE THREAD

**Issue by imev2023** [KChen-lab/Monopogen#83]
Hello, 

I have been running through the germline using the example .bam files (A and B). I have run the code for Chr20 and Chr19 but both results yield .gl.vcf.gz files of 0 bytes when unzipped. I have attached my runGermline_ scripts below. 
I am wondering if this could be due to using the whole genome as the reference, although I assumed it contains both Chr20 and 19 so should not cause any issues. 

Thank you in advance for having a look. 

[runGermline_Terminal_Output.txt](https://github.com/user-attachments/files/17383704/runGermline_Terminal_Output.txt)
[runGermline_chr20.txt](https://github.com/user-attachments/files/17383695/runGermline_chr20.txt)
[runGermline_chr19.txt](https://github.com/user-attachments/files/17383696/runGermline_chr19.txt)

![image](https://github.com/user-attachments/assets/d5fa3ddc-c564-4548-ba56-5dfc874bf1ec)

**Comment by kyleYin7** [comment]
how to solve it, i get Empty .gl.vcf.gz files, too . @imev2023
